### ISSUE TITLE
Removal of json gem in chef 11.14.x causes NoMethodError

### ISSUE THREAD

**Issue by dissonanz** [3ofcoins/chef-cookbook-nginx-proxy#2]
This line in `default` recipe fails under chef 11.14.x because a `require 'json'` statement was removed from `lib/chef/json_compat.rb`:

`else JSON[options.to_json] # json roundabout as a deep to_hash`

Error is:

`NoMethodError: undefined method '[]' for JSON:Module`

Both json gem and chef 11.14.x DO support the following syntax:

`else JSON(options.to_json)`

Alternatively, you could require the json gem in the recipe itself.

**Comment by bernardoVale** [comment]
H @dissonanz , This issue it's blocking from using this cookbook. Did you manage to overcome this problem by yourself?

**Comment by mpasternacki** [comment]
Chef 11 is EOL.
